name: '@attakei-lab/rye'
description: 'Setup and use Rye'
author: 'Kazuya Takei <myself@attakei.net>'
inputs:
  python-version:
    description: 'Version Spec of the node version to use.  Examples: 10.6.x, 10.15.1, >=10.15.0'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: 'Install Rye (Linux)'
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        wget https://github.com/mitsuhiko/rye/releases/latest/download/rye-x86_64-linux.gz
        gunzip rye-x86_64-linux.gz
        chmod +x rye-x86_64-linux
        mv rye-x86_64-linux /usr/local/bin/rye
    - name: 'Install Rye (macOS)'
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        wget https://github.com/mitsuhiko/rye/releases/latest/download/rye-x86_64-macos.gz
        gunzip rye-x86_64-macos.gz
        chmod +x rye-x86_64-macos
        mv rye-x86_64-macos /usr/local/bin/rye
    - name: 'Set up python (*nix)'
      if: contains(fromJSON('["Linux", "macOS"]'), runner.os)
      shell: bash
      run: |
        rye pin ${{ inputs.python-version }}
