on: push

jobs:
  test-run:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v3
      - uses: attakei-lab/rye-action@main
        with:
          python-version: '3.11'
      - run:
          rye show
